import { WatchmodeTitle } from '@/types';

export const MOCK_TITLES: WatchmodeTitle[] = [
  {
    id: 1,
    title: 'The Grand Adventure',
    year: 2023,
    imdb_id: 'tt1234567',
    tmdb_id: 12345,
    type: 'movie',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 8.2,
    genre_names: ['Action', 'Adventure'],
    us_rating: 'PG-13',
    plot_overview: 'Two unlikely heroes embark on an epic journey across uncharted lands to save their world from an ancient evil.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 95,
    sources: [],
  },
  {
    id: 2,
    title: 'Midnight Comedy Club',
    year: 2022,
    imdb_id: 'tt2345678',
    tmdb_id: 23456,
    type: 'tv_series',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 7.8,
    genre_names: ['Comedy', 'Drama'],
    us_rating: 'TV-MA',
    plot_overview: 'A group of comedians navigate the ups and downs of life in New York City, finding humor in everyday struggles.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 88,
    sources: [],
  },
  {
    id: 3,
    title: 'Dark Horizons',
    year: 2023,
    imdb_id: 'tt3456789',
    tmdb_id: 34567,
    type: 'tv_series',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 9.0,
    genre_names: ['Thriller', 'Mystery', 'Drama'],
    us_rating: 'TV-MA',
    plot_overview: 'A detective unravels a conspiracy that goes deeper than anyone imagined, risking everything to expose the truth.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 97,
    sources: [],
  },
  {
    id: 4,
    title: 'Galactic Wanderers',
    year: 2022,
    imdb_id: 'tt4567890',
    tmdb_id: 45678,
    type: 'movie',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 7.5,
    genre_names: ['Science Fiction', 'Adventure'],
    us_rating: 'PG-13',
    plot_overview: "A crew of astronauts discovers a mysterious signal from deep space that could change humanity's understanding of the universe.",
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 82,
    sources: [],
  },
  {
    id: 5,
    title: 'Love in the Rain',
    year: 2023,
    imdb_id: 'tt5678901',
    tmdb_id: 56789,
    type: 'movie',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 7.2,
    genre_names: ['Romance', 'Drama'],
    us_rating: 'PG-13',
    plot_overview: 'Two strangers meet during a storm and discover that sometimes the best love stories begin in the most unexpected ways.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 78,
    sources: [],
  },
  {
    id: 6,
    title: 'The Last Kingdom',
    year: 2022,
    imdb_id: 'tt6789012',
    tmdb_id: 67890,
    type: 'tv_series',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 8.7,
    genre_names: ['History', 'Drama', 'War'],
    us_rating: 'TV-MA',
    plot_overview: 'A noble warrior fights to reclaim his birthright and unite a kingdom torn apart by war and betrayal.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 93,
    sources: [],
  },
  {
    id: 7,
    title: 'Haunted Hollow',
    year: 2023,
    imdb_id: 'tt7890123',
    tmdb_id: 78901,
    type: 'movie',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 7.0,
    genre_names: ['Horror', 'Mystery'],
    us_rating: 'R',
    plot_overview: 'A family moves into their dream home only to discover the dark secrets buried within its walls.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 75,
    sources: [],
  },
  {
    id: 8,
    title: 'Laugh Track',
    year: 2022,
    imdb_id: 'tt8901234',
    tmdb_id: 89012,
    type: 'tv_series',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 8.1,
    genre_names: ['Comedy'],
    us_rating: 'TV-14',
    plot_overview: 'A workplace comedy following the misadventures of an eclectic team at a struggling television network.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 87,
    sources: [],
  },
  {
    id: 9,
    title: "Ocean's Depth",
    year: 2023,
    imdb_id: 'tt9012345',
    tmdb_id: 90123,
    type: 'movie',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 8.4,
    genre_names: ['Adventure', 'Drama'],
    us_rating: 'PG',
    plot_overview: 'Marine biologists uncover a previously unknown ecosystem at the bottom of the Pacific Ocean with astonishing implications.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 91,
    sources: [],
  },
  {
    id: 10,
    title: 'City of Shadows',
    year: 2022,
    imdb_id: 'tt0123456',
    tmdb_id: 1234,
    type: 'tv_series',
    poster: null,
    backdrop: null,
    original_language: 'en',
    imdb_rating: 8.9,
    genre_names: ['Crime', 'Thriller', 'Drama'],
    us_rating: 'TV-MA',
    plot_overview: 'In a corrupt city, a lone journalist risks their life to expose the criminal syndicate controlling every level of power.',
    trailer: null,
    trailer_thumbnail: null,
    relevance_percentile: 96,
    sources: [],
  },
];
